//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Controles.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controles : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controles()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controles"",
    ""maps"": [
        {
            ""name"": ""Juego"",
            ""id"": ""65299913-f24c-433b-a9d5-dd390036515e"",
            ""actions"": [
                {
                    ""name"": ""Movmiento"",
                    ""type"": ""Value"",
                    ""id"": ""0f87cde7-73b4-4892-8e7c-9563ff57b2e0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""disparo"",
                    ""type"": ""Button"",
                    ""id"": ""92211f03-8a34-4bd9-9ea4-516aaf84600b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""0e70d706-a9cd-4199-bb82-7de114492e1b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotar"",
                    ""type"": ""Value"",
                    ""id"": ""d404681e-e8db-49d8-a058-23a815917a2a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ebe79489-6c35-45c6-aac9-aff59b80a7ed"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movmiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""562a3e06-5800-4599-a6c6-5899e150c5c6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movmiento"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8204538c-845c-4a67-bd34-597798409777"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movmiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4fc8f818-158c-46cc-9403-daf759d7e1be"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movmiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5e9234eb-6e64-4439-9500-52582d785f2a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movmiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""98714bdf-a125-4aab-9b66-52e1071f0800"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movmiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""8b850d2e-0b32-46bc-b620-bf3677d364f7"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movmiento"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1e38cff8-071e-4c04-a5f2-c9d9476ef3a6"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movmiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""73fc83d3-7abe-4a40-b968-cc96e19ec128"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movmiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4a583ad6-9432-4759-8087-ce83e23919e5"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movmiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4ab540e4-39a4-44e5-8eb6-fa808c8c92db"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movmiento"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""cea1f35c-7803-4857-ab8d-0e8fb2ffdd77"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""disparo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97020df8-6ada-44e9-bced-c75aef57ab0e"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""disparo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e70bd1da-0b2e-43cc-9419-d51e4773d565"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6273292a-bb7c-405d-867a-bf35d0ead23f"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""48d838bf-9cf8-4a3b-9292-91fe50ce8aec"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotar"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b1d3c090-2e3c-4219-9402-f3c754919d0b"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c64eadce-9409-4624-814d-6da7992d020c"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1c82039e-ad51-4881-a3d3-6d794bee0743"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3905a7c3-2c0e-49bd-b49f-00ce38b5f6bd"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""MenuInsertar"",
            ""id"": ""452c4083-675d-4ed2-a460-8c2331ac849a"",
            ""actions"": [
                {
                    ""name"": ""Aceptar"",
                    ""type"": ""Button"",
                    ""id"": ""94cdfc58-f312-4b84-8e9b-4763b8054a8c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b0df3457-e9f0-43a7-98e7-8272d5f553ca"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aceptar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d50512d2-5c93-4e3b-9f14-3385f0aa6dd4"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aceptar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MenuPausa"",
            ""id"": ""cbf9c983-a8d3-4533-b3f1-43a7483914da"",
            ""actions"": [
                {
                    ""name"": ""EntrarMenu"",
                    ""type"": ""Button"",
                    ""id"": ""eb066835-2d3a-48a7-a1e0-eed9b1d1d42c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Moverse"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5b360509-c87e-4c62-a996-3607f960b4ff"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SalirMenu"",
                    ""type"": ""Button"",
                    ""id"": ""358a59a6-438b-469f-b037-39c3ce3608ec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aceptar"",
                    ""type"": ""Button"",
                    ""id"": ""9c35599f-dbf7-45fd-a865-088560e1ae95"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""62e51c95-de9f-4445-9938-e3fc03fc9d26"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EntrarMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fbbfd41c-204d-4718-b66f-8bd2c33fe62f"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EntrarMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""87076c5d-81b7-49e9-9172-0f6f0ff30920"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d7c04082-93b0-4adc-b05f-f68c257b8d05"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""52ba7975-ee43-4f72-bddb-eb8253b7d69e"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9e897a5b-bd99-49ed-8dc4-01dbfc8ffc9f"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""76037be8-8935-43e1-9dd2-f0baa549a41b"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Teclas"",
                    ""id"": ""4f414e01-9e5b-454f-b9ad-39c2e71b8904"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6d6e3995-0570-48d8-9d9d-6e163c8230fa"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1385c96d-5250-402f-8ef8-e7e6b4bb4ea4"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""510e4562-c1a3-445c-8189-96c49a2d7712"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b7d69d35-a2aa-4e6e-a387-edc82f276440"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b54bfad5-e2bb-44a2-b9e4-3b030db26be5"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SalirMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e88b169-44e6-4a76-a0a3-1f295d83af8d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aceptar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""33724935-bcdd-42bf-afa6-48c9fb403c42"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aceptar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MenuPrincipal"",
            ""id"": ""523104cd-5e50-4ff5-a118-9d9c7e69f277"",
            ""actions"": [
                {
                    ""name"": ""Moverse"",
                    ""type"": ""PassThrough"",
                    ""id"": ""af02ea09-fab0-4072-8eb4-9a2539c9b101"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aceptar"",
                    ""type"": ""Button"",
                    ""id"": ""aa4fb873-077f-4720-99d4-85db50e80121"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""1c9c2af7-ebcb-4467-a9b4-cde370e57277"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""bafcbfaa-ac12-4f8c-8c86-a3638c6c9911"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6c208d47-f1d6-4c5d-9260-61549a64850b"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""70a19ea4-ee66-4bb0-8ad0-af4b6edd7312"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d4bc1f56-0137-4787-9516-6928dcfd569b"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""34842dda-344f-4164-8768-45d1f4d96c43"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aceptar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Juego
        m_Juego = asset.FindActionMap("Juego", throwIfNotFound: true);
        m_Juego_Movmiento = m_Juego.FindAction("Movmiento", throwIfNotFound: true);
        m_Juego_disparo = m_Juego.FindAction("disparo", throwIfNotFound: true);
        m_Juego_Dash = m_Juego.FindAction("Dash", throwIfNotFound: true);
        m_Juego_Rotar = m_Juego.FindAction("Rotar", throwIfNotFound: true);
        // MenuInsertar
        m_MenuInsertar = asset.FindActionMap("MenuInsertar", throwIfNotFound: true);
        m_MenuInsertar_Aceptar = m_MenuInsertar.FindAction("Aceptar", throwIfNotFound: true);
        // MenuPausa
        m_MenuPausa = asset.FindActionMap("MenuPausa", throwIfNotFound: true);
        m_MenuPausa_EntrarMenu = m_MenuPausa.FindAction("EntrarMenu", throwIfNotFound: true);
        m_MenuPausa_Moverse = m_MenuPausa.FindAction("Moverse", throwIfNotFound: true);
        m_MenuPausa_SalirMenu = m_MenuPausa.FindAction("SalirMenu", throwIfNotFound: true);
        m_MenuPausa_Aceptar = m_MenuPausa.FindAction("Aceptar", throwIfNotFound: true);
        // MenuPrincipal
        m_MenuPrincipal = asset.FindActionMap("MenuPrincipal", throwIfNotFound: true);
        m_MenuPrincipal_Moverse = m_MenuPrincipal.FindAction("Moverse", throwIfNotFound: true);
        m_MenuPrincipal_Aceptar = m_MenuPrincipal.FindAction("Aceptar", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Juego
    private readonly InputActionMap m_Juego;
    private IJuegoActions m_JuegoActionsCallbackInterface;
    private readonly InputAction m_Juego_Movmiento;
    private readonly InputAction m_Juego_disparo;
    private readonly InputAction m_Juego_Dash;
    private readonly InputAction m_Juego_Rotar;
    public struct JuegoActions
    {
        private @Controles m_Wrapper;
        public JuegoActions(@Controles wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movmiento => m_Wrapper.m_Juego_Movmiento;
        public InputAction @disparo => m_Wrapper.m_Juego_disparo;
        public InputAction @Dash => m_Wrapper.m_Juego_Dash;
        public InputAction @Rotar => m_Wrapper.m_Juego_Rotar;
        public InputActionMap Get() { return m_Wrapper.m_Juego; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(JuegoActions set) { return set.Get(); }
        public void SetCallbacks(IJuegoActions instance)
        {
            if (m_Wrapper.m_JuegoActionsCallbackInterface != null)
            {
                @Movmiento.started -= m_Wrapper.m_JuegoActionsCallbackInterface.OnMovmiento;
                @Movmiento.performed -= m_Wrapper.m_JuegoActionsCallbackInterface.OnMovmiento;
                @Movmiento.canceled -= m_Wrapper.m_JuegoActionsCallbackInterface.OnMovmiento;
                @disparo.started -= m_Wrapper.m_JuegoActionsCallbackInterface.OnDisparo;
                @disparo.performed -= m_Wrapper.m_JuegoActionsCallbackInterface.OnDisparo;
                @disparo.canceled -= m_Wrapper.m_JuegoActionsCallbackInterface.OnDisparo;
                @Dash.started -= m_Wrapper.m_JuegoActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_JuegoActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_JuegoActionsCallbackInterface.OnDash;
                @Rotar.started -= m_Wrapper.m_JuegoActionsCallbackInterface.OnRotar;
                @Rotar.performed -= m_Wrapper.m_JuegoActionsCallbackInterface.OnRotar;
                @Rotar.canceled -= m_Wrapper.m_JuegoActionsCallbackInterface.OnRotar;
            }
            m_Wrapper.m_JuegoActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movmiento.started += instance.OnMovmiento;
                @Movmiento.performed += instance.OnMovmiento;
                @Movmiento.canceled += instance.OnMovmiento;
                @disparo.started += instance.OnDisparo;
                @disparo.performed += instance.OnDisparo;
                @disparo.canceled += instance.OnDisparo;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @Rotar.started += instance.OnRotar;
                @Rotar.performed += instance.OnRotar;
                @Rotar.canceled += instance.OnRotar;
            }
        }
    }
    public JuegoActions @Juego => new JuegoActions(this);

    // MenuInsertar
    private readonly InputActionMap m_MenuInsertar;
    private IMenuInsertarActions m_MenuInsertarActionsCallbackInterface;
    private readonly InputAction m_MenuInsertar_Aceptar;
    public struct MenuInsertarActions
    {
        private @Controles m_Wrapper;
        public MenuInsertarActions(@Controles wrapper) { m_Wrapper = wrapper; }
        public InputAction @Aceptar => m_Wrapper.m_MenuInsertar_Aceptar;
        public InputActionMap Get() { return m_Wrapper.m_MenuInsertar; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuInsertarActions set) { return set.Get(); }
        public void SetCallbacks(IMenuInsertarActions instance)
        {
            if (m_Wrapper.m_MenuInsertarActionsCallbackInterface != null)
            {
                @Aceptar.started -= m_Wrapper.m_MenuInsertarActionsCallbackInterface.OnAceptar;
                @Aceptar.performed -= m_Wrapper.m_MenuInsertarActionsCallbackInterface.OnAceptar;
                @Aceptar.canceled -= m_Wrapper.m_MenuInsertarActionsCallbackInterface.OnAceptar;
            }
            m_Wrapper.m_MenuInsertarActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Aceptar.started += instance.OnAceptar;
                @Aceptar.performed += instance.OnAceptar;
                @Aceptar.canceled += instance.OnAceptar;
            }
        }
    }
    public MenuInsertarActions @MenuInsertar => new MenuInsertarActions(this);

    // MenuPausa
    private readonly InputActionMap m_MenuPausa;
    private IMenuPausaActions m_MenuPausaActionsCallbackInterface;
    private readonly InputAction m_MenuPausa_EntrarMenu;
    private readonly InputAction m_MenuPausa_Moverse;
    private readonly InputAction m_MenuPausa_SalirMenu;
    private readonly InputAction m_MenuPausa_Aceptar;
    public struct MenuPausaActions
    {
        private @Controles m_Wrapper;
        public MenuPausaActions(@Controles wrapper) { m_Wrapper = wrapper; }
        public InputAction @EntrarMenu => m_Wrapper.m_MenuPausa_EntrarMenu;
        public InputAction @Moverse => m_Wrapper.m_MenuPausa_Moverse;
        public InputAction @SalirMenu => m_Wrapper.m_MenuPausa_SalirMenu;
        public InputAction @Aceptar => m_Wrapper.m_MenuPausa_Aceptar;
        public InputActionMap Get() { return m_Wrapper.m_MenuPausa; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuPausaActions set) { return set.Get(); }
        public void SetCallbacks(IMenuPausaActions instance)
        {
            if (m_Wrapper.m_MenuPausaActionsCallbackInterface != null)
            {
                @EntrarMenu.started -= m_Wrapper.m_MenuPausaActionsCallbackInterface.OnEntrarMenu;
                @EntrarMenu.performed -= m_Wrapper.m_MenuPausaActionsCallbackInterface.OnEntrarMenu;
                @EntrarMenu.canceled -= m_Wrapper.m_MenuPausaActionsCallbackInterface.OnEntrarMenu;
                @Moverse.started -= m_Wrapper.m_MenuPausaActionsCallbackInterface.OnMoverse;
                @Moverse.performed -= m_Wrapper.m_MenuPausaActionsCallbackInterface.OnMoverse;
                @Moverse.canceled -= m_Wrapper.m_MenuPausaActionsCallbackInterface.OnMoverse;
                @SalirMenu.started -= m_Wrapper.m_MenuPausaActionsCallbackInterface.OnSalirMenu;
                @SalirMenu.performed -= m_Wrapper.m_MenuPausaActionsCallbackInterface.OnSalirMenu;
                @SalirMenu.canceled -= m_Wrapper.m_MenuPausaActionsCallbackInterface.OnSalirMenu;
                @Aceptar.started -= m_Wrapper.m_MenuPausaActionsCallbackInterface.OnAceptar;
                @Aceptar.performed -= m_Wrapper.m_MenuPausaActionsCallbackInterface.OnAceptar;
                @Aceptar.canceled -= m_Wrapper.m_MenuPausaActionsCallbackInterface.OnAceptar;
            }
            m_Wrapper.m_MenuPausaActionsCallbackInterface = instance;
            if (instance != null)
            {
                @EntrarMenu.started += instance.OnEntrarMenu;
                @EntrarMenu.performed += instance.OnEntrarMenu;
                @EntrarMenu.canceled += instance.OnEntrarMenu;
                @Moverse.started += instance.OnMoverse;
                @Moverse.performed += instance.OnMoverse;
                @Moverse.canceled += instance.OnMoverse;
                @SalirMenu.started += instance.OnSalirMenu;
                @SalirMenu.performed += instance.OnSalirMenu;
                @SalirMenu.canceled += instance.OnSalirMenu;
                @Aceptar.started += instance.OnAceptar;
                @Aceptar.performed += instance.OnAceptar;
                @Aceptar.canceled += instance.OnAceptar;
            }
        }
    }
    public MenuPausaActions @MenuPausa => new MenuPausaActions(this);

    // MenuPrincipal
    private readonly InputActionMap m_MenuPrincipal;
    private IMenuPrincipalActions m_MenuPrincipalActionsCallbackInterface;
    private readonly InputAction m_MenuPrincipal_Moverse;
    private readonly InputAction m_MenuPrincipal_Aceptar;
    public struct MenuPrincipalActions
    {
        private @Controles m_Wrapper;
        public MenuPrincipalActions(@Controles wrapper) { m_Wrapper = wrapper; }
        public InputAction @Moverse => m_Wrapper.m_MenuPrincipal_Moverse;
        public InputAction @Aceptar => m_Wrapper.m_MenuPrincipal_Aceptar;
        public InputActionMap Get() { return m_Wrapper.m_MenuPrincipal; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuPrincipalActions set) { return set.Get(); }
        public void SetCallbacks(IMenuPrincipalActions instance)
        {
            if (m_Wrapper.m_MenuPrincipalActionsCallbackInterface != null)
            {
                @Moverse.started -= m_Wrapper.m_MenuPrincipalActionsCallbackInterface.OnMoverse;
                @Moverse.performed -= m_Wrapper.m_MenuPrincipalActionsCallbackInterface.OnMoverse;
                @Moverse.canceled -= m_Wrapper.m_MenuPrincipalActionsCallbackInterface.OnMoverse;
                @Aceptar.started -= m_Wrapper.m_MenuPrincipalActionsCallbackInterface.OnAceptar;
                @Aceptar.performed -= m_Wrapper.m_MenuPrincipalActionsCallbackInterface.OnAceptar;
                @Aceptar.canceled -= m_Wrapper.m_MenuPrincipalActionsCallbackInterface.OnAceptar;
            }
            m_Wrapper.m_MenuPrincipalActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Moverse.started += instance.OnMoverse;
                @Moverse.performed += instance.OnMoverse;
                @Moverse.canceled += instance.OnMoverse;
                @Aceptar.started += instance.OnAceptar;
                @Aceptar.performed += instance.OnAceptar;
                @Aceptar.canceled += instance.OnAceptar;
            }
        }
    }
    public MenuPrincipalActions @MenuPrincipal => new MenuPrincipalActions(this);
    public interface IJuegoActions
    {
        void OnMovmiento(InputAction.CallbackContext context);
        void OnDisparo(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnRotar(InputAction.CallbackContext context);
    }
    public interface IMenuInsertarActions
    {
        void OnAceptar(InputAction.CallbackContext context);
    }
    public interface IMenuPausaActions
    {
        void OnEntrarMenu(InputAction.CallbackContext context);
        void OnMoverse(InputAction.CallbackContext context);
        void OnSalirMenu(InputAction.CallbackContext context);
        void OnAceptar(InputAction.CallbackContext context);
    }
    public interface IMenuPrincipalActions
    {
        void OnMoverse(InputAction.CallbackContext context);
        void OnAceptar(InputAction.CallbackContext context);
    }
}
